#+TITLE: Readme

* Intro

We are a group of musicians and sonic intermedia artists from Greece, working with SuperCollider as well as with related other environments for live sound and graphics synthesis.  We use OSCGroups to explore ways for collaborative performance over the internet.  In particular, using the library sc-hacks-redux and OscGroups servers set up on the cloud, we are able to perform in groups while sharing both code and data over the internet, so that the local computer of each musician runs an exact mirror of the entire performance (code and data) at each moment (similar to gemers sharing a multiplayer real-time virtual world).  We are looking to attract other groups in order to create performances where we collaborate live over the internet, creating simultaneous performances of the same work in remotely located venues anywhere in the world.  As first milestone to test this idea we have issued the following call:

* Supported technololgies, tools, ideas for works

* Background, Motivation

* Objectives

* Tools

* Networks, Partners, Social

** Facebook Groups

** Resreach and Art Organizations

** Individual Artits
